# Generated by Django 3.2.15 on 2022-09-13 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followup', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('magnet_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=255)),
                ('id_verification_status', models.IntegerField(default=0)),
                ('legal_status', models.IntegerField(default=0)),
                ('magnet_created_by', models.IntegerField(default=0)),
                ('aecode', models.CharField(default='', max_length=25)),
                ('demologin', models.IntegerField(default=0)),
                ('cdd', models.BooleanField(default=False)),
                ('create_ip', models.CharField(default='', max_length=32)),
                ('medium', models.CharField(default='', max_length=50)),
                ('campaign', models.CharField(default='', max_length=50)),
                ('term', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=50)),
                ('gclid', models.CharField(default='', max_length=128)),
                ('magnet_created_at', models.DateTimeField(blank=True, null=True)),
                ('magnet_update_at', models.DateTimeField(blank=True, null=True)),
                ('umur', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(default='', max_length=255)),
                ('pekerjaan', models.CharField(default='', max_length=255)),
                ('domisili', models.CharField(default='', max_length=255)),
                ('phone_no', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_registred', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_suspect', models.BooleanField(default=False)),
                ('magnet_id', models.CharField(default='', max_length=255)),
                ('source', models.CharField(choices=[('0', 'Fresh Data'), ('1', 'Rolling Data'), ('2', 'External Data')], default='0', max_length=255)),
                ('source_detail_1', models.CharField(choices=[('0', 'Leads Ads'), ('1', 'Organic'), ('2', 'Pribadi Marketing'), ('3', 'IB'), ('4', 'Rolling Data Regis '), ('5', 'Rolling Data Inactive Client')], default='3', max_length=255)),
                ('source_detail_2', models.CharField(blank=True, choices=[('0', 'Adwords'), ('1', 'Facbook'), ('2', 'Social Media'), ('3', 'Email'), ('4', 'Google')], default=None, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('color', models.CharField(default='ff0000', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_staff_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_staff_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('phone', 'Phone'), ('email', 'Email'), ('offfline_meeting', 'Offline Meeting'), ('other', 'Others')], default='whatsapp', max_length=255)),
                ('status', models.CharField(default='', max_length=255)),
                ('notes', models.TextField(default='')),
                ('answer', models.CharField(default='', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_schedule_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_schedule_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('journal_type', models.CharField(choices=[('registered', 'Registered'), ('scheduled_followup', 'Scheduled Followup'), ('feedback', 'Feeback'), ('whatsapp', 'Whatsapp'), ('called', 'Called'), ('emailed', 'Emailed'), ('changed_fc', 'Change FC')], max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_journey_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_journey_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('answer', models.CharField(default='', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_followup_created_by', to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followup.followup')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_followup_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Duplicate_Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('client_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_Duplicate_Suspect_Client_New', to='client.client')),
                ('client_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_Duplicate_Suspect_Client_Old', to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_duplicate_suspect_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_duplicate_suspect_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
