# Generated by Django 3.2.15 on 2022-08-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220820_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='profile',
        ),
        migrations.AddField(
            model_name='client',
            name='domisili',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='nama',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='pekerjaan',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='umur',
            field=models.CharField(default='', max_length=255),
        ),
    ]
