# Generated by Django 3.2.15 on 2022-09-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_staff_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_suspect_bypass',
            field=models.BooleanField(default=False),
        ),
    ]
