# Generated by Django 3.2.15 on 2022-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20220820_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
