# Generated by Django 3.2.15 on 2022-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20220822_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_schedule',
            name='schedule_type',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('phone', 'Phone'), ('email', 'Email'), ('other', 'Others')], default='whatsapp', max_length=255),
        ),
    ]
