# Generated by Django 3.2.15 on 2022-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_schedule_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_schedule',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
