# Generated by Django 3.2.15 on 2022-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_clientjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientjournal',
            name='journal_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('scheduled_followup', 'Scheduled Followup'), ('feedback', 'Feeback'), ('whatsapp', 'Whatsapp'), ('called', 'Called'), ('emailed', 'Emailed'), ('changed_fc', 'Change FC')], max_length=255),
        ),
    ]
