# Generated by Django 3.2.15 on 2022-09-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('client', '0010_alter_client_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_journey',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
