# Generated by Django 3.2.15 on 2022-09-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_client_journey_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_registred',
            new_name='is_registered',
        ),
    ]
