# Generated by Django 3.2.15 on 2022-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20220823_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_staff',
            name='color',
            field=models.CharField(default='#FF0000', max_length=255),
        ),
    ]
