# Generated by Django 3.2.15 on 2022-09-20 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0012_rename_is_registred_client_is_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Scramble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_scramble_created_by', to=settings.AUTH_USER_MODEL)),
                ('from_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_Scramble_From_Staff', to='staff.staff')),
                ('staff_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_Scramble_Staff_Parent', to='staff.staff')),
                ('to_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_Scramble_To_Staff', to='staff.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_scramble_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
