# Generated by Django 3.2.15 on 2022-09-22 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0013_client_scramble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Duplicate_Suspect_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('accepted', 'Accpeted'), ('rejected', 'Rejected')], max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_duplicate_suspect_history_created_by', to=settings.AUTH_USER_MODEL)),
                ('duplicate_suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_duplicate_suspect')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_duplicate_suspect_history_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
