# Generated by Django 3.2.15 on 2022-10-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_client_duplicate_suspect_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
