# Generated by Django 3.2.15 on 2022-08-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_client_staff_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='source_detail_1',
            field=models.CharField(choices=[('0', 'Leads Ads'), ('1', 'Organic'), ('2', 'Pribadi Marketing'), ('3', 'IB'), ('4', 'Rolling Data Regis '), ('5', 'Rolling Data Inactive Client')], default='3', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='source_detail_2',
            field=models.CharField(blank=True, choices=[('0', 'Adwords'), ('1', 'Facbook'), ('2', 'Social Media'), ('3', 'Email'), ('4', 'Google')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('0', 'Fresh Data'), ('1', 'Rolling Data')], default='0', max_length=255),
        ),
    ]
