# Generated by Django 3.2.15 on 2022-10-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_client_is_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_staff',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
