# Generated by Django 3.2.15 on 2022-10-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_client_staff_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='source_detail_1',
            field=models.CharField(blank=True, choices=[('0', 'Leads Ads'), ('1', 'Organic'), ('2', 'Pribadi Marketing'), ('3', 'IB'), ('4', 'Rolling Data Regis'), ('5', 'Rolling Data Inactive Client')], default='3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='source_detail_2',
            field=models.CharField(blank=True, choices=[('0', 'Adwords'), ('1', 'Facebook'), ('2', 'Social Media'), ('3', 'Email'), ('4', 'Google')], default=None, max_length=255, null=True),
        ),
    ]
