# Generated by Django 3.2.15 on 2022-08-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_client_schedule_schedule_type'),
        ('client', '0016_auto_20220826_0519'),
    ]

    operations = [
    ]
