# Generated by Django 3.2.15 on 2022-11-01 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0017_auto_20221031_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Staff_Voip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('called_date', models.DateTimeField(blank=True, null=True)),
                ('callend_end_date', models.DateField(blank=True, null=True)),
                ('is_answer', models.BooleanField(default=False)),
                ('client_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_staff')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_staff_voip_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_staff_voip_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
