# Generated by Django 3.2.15 on 2022-08-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_merge_20220826_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
