# Generated by Django 3.2.15 on 2022-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20221128_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='source_detail_1',
            field=models.CharField(blank=True, choices=[('0', 'Leads Ads'), ('1', 'Organic'), ('2', 'Pribadi Marketing'), ('3', 'IB'), ('4', 'Rolling Data Regis'), ('5', 'Rolling Data Inactive Client')], default=None, max_length=255, null=True),
        ),
    ]
