# Generated by Django 3.2.15 on 2022-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20220829_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_suspect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='magnet_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
