# Generated by Django 3.2.15 on 2022-09-12 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0020_auto_20220908_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Duplicate_Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('client_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_Duplicate_Suspect_Client_New', to='client.client')),
                ('client_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_Duplicate_Suspect_Client_Old', to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_client_duplicate_suspect_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_duplicate_suspect_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
