# Generated by Django 3.2.15 on 2022-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_client_is_ib'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_journey',
            name='extra',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client_journey',
            name='journal_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('scheduled_followup', 'Scheduled Followup'), ('feedback', 'Feeback'), ('whatsapp', 'Whatsapp'), ('called', 'Called'), ('emailed', 'Emailed'), ('changed_fc', 'Change FC'), ('login_created', 'Login Creaated')], max_length=255),
        ),
    ]
