# Generated by Django 3.2.15 on 2022-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20221207_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='campaign',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='content',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='medium',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='term',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
