# Generated by Django 3.2.15 on 2023-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_auto_20221208_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='shared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
