# Generated by Django 3.2.15 on 2022-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
