# Generated by Django 3.2.15 on 2022-08-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20220829_1646'),
        ('notification', '0002_alter_notification_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('notification_followup', 'Notification Followup'), ('birthday', 'Birthday'), ('new_clients', 'New Clients')], max_length=255),
        ),
    ]
