# Generated by Django 3.2.15 on 2022-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_level',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
