# Generated by Django 3.2.15 on 2022-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_level_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_level',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
