# Generated by Django 3.2.15 on 2022-08-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0002_alter_staff_staff_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff_level'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staff_history',
            name='child_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Staff_History_Child_Staff', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staff_history',
            name='parent_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Staff_History_Parent_Staff', to='staff.staff'),
        ),
    ]
