# Generated by Django 3.2.15 on 2022-11-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_level_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_fc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_ib',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_spv',
            field=models.BooleanField(default=False),
        ),
    ]
