# Generated by Django 3.2.15 on 2022-11-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20221101_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aecode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
