# Generated by Django 3.2.15 on 2022-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20220820_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
