# Generated by Django 3.2.15 on 2022-11-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_aecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rekening',
            field=models.CharField(default='', max_length=255),
        ),
    ]
