# Generated by Django 3.2.15 on 2022-08-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='is_opened',
            field=models.BooleanField(default=True),
        ),
    ]
