# Generated by Django 3.2.15 on 2022-08-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_history',
            name='staff_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_History_Staff_Level', to='staff.staff_level'),
        ),
    ]
