# Generated by Django 3.2.15 on 2022-08-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_history_staff_level'),
        ('staff', '0007_staff_notification_is_opened'),
    ]

    operations = [
    ]
