# Generated by Django 3.2.15 on 2022-08-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_merge_20220826_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_Notification',
        ),
    ]
