# Generated by Django 3.2.15 on 2022-08-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_merge_20220826_0841'),
        ('staff', '0009_delete_staff_notification'),
    ]

    operations = [
    ]
