# Generated by Django 3.2.15 on 2022-08-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_merge_20220826_1004'),
        ('staff', '0010_merge_20220826_1028'),
    ]

    operations = [
    ]
