# Generated by Django 3.2.15 on 2022-09-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0012_staff_salary_staff_salary_montly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Salary_Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('salary_date', models.DateField(blank=True, null=True)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_staff_salary_monthly_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_staff_salary_monthly_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Staff_Salary_Montly',
        ),
    ]
