# Generated by Django 3.2.15 on 2022-09-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staff_salary_staff_salary_montly'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_salary_montly',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
