# Generated by Django 3.2.15 on 2022-09-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20220908_1144'),
        ('staff', '0013_staff_salary_montly_staff'),
    ]

    operations = [
    ]
