# Generated by Django 3.2.15 on 2022-09-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_merge_20220909_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_salary_monthly',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
            preserve_default=False,
        ),
    ]
