# Generated by Django 3.2.15 on 2022-09-08 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0020_auto_20220908_1144'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0013_auto_20220908_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Client_Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bonus_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Client_Bonus_client', to='client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_staff_client_bonus_created_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff_Client_Bonus_Staff', to='staff.staff')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_staff_client_bonus_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
