# Generated by Django 3.2.15 on 2022-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_choices', models.CharField(default='', max_length=255)),
                ('followup_choice_code', models.TextField(default='')),
            ],
        ),
    ]
