# Generated by Django 3.2.15 on 2022-08-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='followup_choice_head',
            field=models.TextField(default=''),
        ),
    ]
