# Generated by Django 3.2.15 on 2022-08-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_auto_20220820_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='color',
            field=models.CharField(default='0c83e2', max_length=255),
        ),
    ]
