# Generated by Django 3.2.15 on 2022-08-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_followup_followup_choice_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_selected_code', models.TextField(default='')),
            ],
        ),
    ]
