# Generated by Django 3.2.15 on 2022-08-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_followupselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='foolowup_textfield',
            field=models.BooleanField(default=False),
        ),
    ]
