# Generated by Django 3.2.15 on 2022-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_followup_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='color',
            field=models.CharField(default='#0c83e2', max_length=255),
        ),
    ]
