# Generated by Django 3.2.15 on 2022-08-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0004_followup_foolowup_textfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='foolowup_textfield',
            new_name='followup_textfield',
        ),
    ]
