# Generated by Django 3.2.15 on 2022-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0004_alter_followup_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='font_color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
    ]
