# Generated by Django 3.2.15 on 2023-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib', '0002_ib_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ib',
            name='aecode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
